# Generated by Django 3.1.6 on 2021-02-24 16:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AmarakuModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('memo', models.TextField(blank=True, null=True)),
                ('url_ama', models.URLField(blank=True, default='', max_length=1000, null=True)),
                ('url_raku', models.URLField(blank=True, default='', max_length=1000, null=True)),
                ('price_ama', models.IntegerField(blank=True, null=True)),
                ('price_raku', models.IntegerField(blank=True, null=True)),
                ('lowest_ama', models.IntegerField(blank=True, null=True)),
                ('lowest_raku', models.IntegerField(blank=True, null=True)),
                ('register_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('last_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
    ]
