# Generated by Django 3.1.6 on 2021-02-27 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tubesearchapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tubesearchmodel',
            name='videos',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
