# Generated by Django 3.1.6 on 2021-02-27 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tubesearchapp', '0002_tubesearchmodel_videos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tubesearchmodel',
            name='videos',
        ),
    ]
