# Generated by Django 3.1.6 on 2021-02-24 12:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('amarakuapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='amarakumodel',
            name='last_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='amarakumodel',
            name='register_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
